version: '3'

services:
  nginx-frontend-app:
    container_name: nginx-frontend-app
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
    networks:
      - app-network
      
  apache-backend-app:
    build:
      context: ./backend
    container_name: apache-backend-app
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql-app

  mysql-app:
    image: mysql:8.0.30
    container_name: mysql-app
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qBLCW1O
      MYSQL_DATABASE: gruporeport-app
      MYSQL_USER: app_root
      MYSQL_PASSWORD: app_password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: